on: push

name: Build and deploy
jobs:
  buildAndDeploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout branch
      uses: actions/checkout@master
    - name: Install dependencies
      uses: actions/npm@master
      with:
        args: install
    - name: Build the solution
      uses: actions/npm@master
      with:
        args: "run-script build:prod"
    - name: Deploy the solution
      uses: contention/rsync-deployments@master
      env:
        DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
        RVM_MACHINE: ${{ secrets.RVM_MACHINE }}
        RVM_USERNAME: ${{ secrets.RVM_USERNAME }}
      with:
        args: -arv --omit-dir-times --files-from=dist/a/ $RVM_USERNAME@$RVM_MACHINE:/var/www/html/
