on: push

name: Build and deploy
jobs:
  buildAndDeploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout branch
      uses: actions/checkout@master
    - name: Install dependencies
      uses: actions/npm@master
      with:
        args: install
    - name: Build the solution
      uses: actions/npm@master
      with:
        args: "run-script build:prod"
