on: push

name: Build and deploy
jobs:
  buildAndDeploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout branch
      uses: actions/checkout@master
      run: Checkout `staging` branch
    - name: Build the solution
      uses: actions/npm@master
      args: "run-script build:prod"
